### ISSUE TITLE
*.markdown.erb files don't have fenced code blocks

### ISSUE THREAD

**Issue by di** [promptworks/promptworks.vim#27]
The ERB and Markdown syntax highlights fine, but not anything embedded. E.g.: 

![screen shot 2016-07-14 at 12 21 06 pm](https://cloud.githubusercontent.com/assets/294415/16847123/6dc689bc-49bd-11e6-914b-c05f7f169cd1.png)

If you change a file to `.markdown`, code blocks work, but ERB does not (as might be expected):

![screen shot 2016-07-14 at 12 23 20 pm](https://cloud.githubusercontent.com/assets/294415/16847174/ac309954-49bd-11e6-8fee-15649243377d.png)

I tried to fix this a couple ways but couldn't. @bduggan @nicholaides any ideas?

**Comment by bduggan** [comment]
Sorry -- not sure I follow the question -- is this a question about syntax highlighting in the editor or about rendering the page?

**Comment by di** [comment]
@bduggan Syntax highlighting in the editor. The filename changes whether fenced code blocks are highlighted or not.

**Comment by bduggan** [comment]
hmm, when I try, I don't see syntax highlighting in code fences even inside a .markdown

**Comment by di** [comment]
Have you pulled recently? I added it in #24.

**Comment by bduggan** [comment]
Got it, now I can reproduce it (oops, was pulling the rcfiles instead...)

**Comment by andrewcroce** [comment]
To be clear, this has nothing to do with the rendering of code blocks in the built HTML?

**Comment by bduggan** [comment]
When I explicitly type `:set syntax=markdown.eruby` it seems to work.  The output of `:set syntax` beforehand is just eruby, so seems related to properly handling the file extension..

**Comment by di** [comment]
@andrewcroce Nope, this is a vim-specific thing.

@bduggan Interesting, I didn't know about `markdown.eruby`, I wonder why the filetype detector didn't pick up on that.
